server:
  port: 8080

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: test
    password: test
    platform: h2
  jpa:
    hibernate:
      ddl-auto: update